<?php
/**
 * @file
 * API for using the MaxMind GeoLite Country database.
 */

/**
 * Implements hook_views_query_substitutions().
 *
 * @todo Finish once port settled.
 */
//function geoip_views_query_substitutions($view) {
//  $cache = &drupal_static(__FUNCTION__, array());
//  // Since evaluating all the details can take some time we cache this per
//  // request, so multiple views won't slow down the execution.
//  if (empty($cache)) {
//    $cache = array(
//      '***GEOIP_CONTINENT_CODE***' => geoip_continent_code(),
//      '***GEOIP_CONTINENT_NAME***' => geoip_continent_name(),
//      '***GEOIP_COUNTRY_CODE***' => geoip_country_code(),
//      '***GEOIP_COUNTRY_NAME***' => geoip_country_name(),
//      '***GEOIP_REGION_CODE***' => geoip_region_code(),
//      '***GEOIP_REGION_NAME***' => geoip_region_name(),
//    );
//  }
//  return $cache;
//}

/**
 * Returns the list with the ISO continents keyed by the continent code.
 *
 * @return array
 *   Associative array key is the continent code, value is the continent name.
 */
function geoip_continents_list() {
  $continents = array(
    'AN' => t('Antarctica'),
    'AF' => t('Africa'),
    'AS' => t('Asia'),
    'EU' => t('Europe'),
    'NA' => t('North America'),
    'OC' => t('Australia (Oceania)'),
    'SA' => t('South America'),
  );
  return $continents;
}
